name: hello-world

on: push

jobs:
  hello-world-job

    runs-on: ubuntu-lateast

    steps:
      - name: check out respository code
        uses: actions/checkout@v4
      - run: echo "$(cat hellp_world.txt)"
